/**
 * Renders JSON-LD. Injected server-side so crawlers and AI agents that do not
 * execute JavaScript still see the structured data.
 */
export function JsonLd({ data }: { data: Record<string, unknown> | Array<Record<string, unknown>> }) {
  return (
    <script
      type="application/ld+json"
      // Content is generated by us, never user input. Escape `<` to prevent
      // any chance of breaking out of the script tag.
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(data).replace(/</g, '\\u003c'),
      }}
    />
  );
}
